// users

// Forms
export const GET_FORMS_SUCCESS = 'GET_FORMS_SUCCESS';
export const GET_FORM_SUCCESS = 'GET_FORM_SUCCESS';

// Documents

export const GET_DOCUMENTS_SUCCESS = 'GET_DOCUMENTS_SUCCESS';
export const GET_DOCUMENT_SUCCESS = 'GET_DOCUMENT_SUCCESS';

// Processes

export const GET_PROCESSES_SUCCESS = 'GET_PROCESSES_SUCCESS';
export const GET_PROCESS_SUCCESS = 'GET_PROCESS_SUCCESS';


// Search Layout
export const LOAD_SEARCH_LAYOUT = 'LOAD_SEARCH_LAYOUT';
